// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://damcpcytilkwwbcymvpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhbWNwY3l0aWxrd3diY3ltdnBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzUzMTgsImV4cCI6MjA3MTQ1MTMxOH0.UQr0Plh2asrSqkLqXxRZ1O_2-Z6QY-azEOlATQLL-OE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});